fix a problem when handling cyclotron sut
EMResearch/EvoMaster pull request #219
Opened 2020-11-26 19:22 UTC by ZhangMan1126

2020-11-27 15:04 UTC, bogdanmarculescu commented
Seems okay to me.

2020-11-27 15:09 UTC, ZhangMan1126 commented
@arcuri82 after discussing with Bogdan, we decide to provide a warning for the problem for the moment. In addition, the problem is also clarified as comments.

2020-11-28 12:18 UTC, arcuri82 requested changes

2020-11-28 12:18 UTC, arcuri82 commented on core/src/main/kotlin/org/evomaster/core/output/oracles/SchemaOracle.kt
> +                        log.warn("missing type of a response with Array schema {}", call.getName())
in the log, add info on endpoint/verb

2020-11-28 13:02 UTC, merged