Map extend
EMResearch/EvoMaster pull request #419
Opened 2021-11-26 12:51 UTC by ZhangMan1126

add pair gene
extend map with pair
tests for update

2021-12-01 14:23 UTC, arcuri82 commented on core/src/main/kotlin/org/evomaster/core/search/gene/MapGene.kt
>          elements.remove(element)
how does this work? doe genes implements `equalsTo`?  or is this assuming heap reference? add clarification

2021-12-01 14:24 UTC, arcuri82 commented on core/src/main/kotlin/org/evomaster/core/search/gene/MapGene.kt
>          elements.remove(element)
to clarify, how/where is this method supposed to be used?
if it is just a matter of removing an element, shouldn't just pass in a reference to the `K`?

2021-12-01 15:15 UTC, ZhangMan1126 commented on core/src/main/kotlin/org/evomaster/core/search/gene/MapGene.kt
> +    fun addElements(element: PairGene<K, V>){
there exist a method `containsKey` to check if the key exists. but now we only support integer, string and long type (see `getElementsBy` in map).
regarding the `addElements`, with a latest commit, now we handle it by 1) adding the new element if the key does not exist, or 2) replacing the existing one with the new element if the key exists;
regarding its mutation, we try to generate an element (key to value) with a key that does not exist in the current list of elements (see `addRandomElement`).

2021-12-02 08:00 UTC, arcuri82 requested changes

2021-12-02 08:00 UTC, arcuri82 commented on core/src/main/kotlin/org/evomaster/core/search/gene/MapGene.kt
> +    fun addElements(element: PairGene<K, V>){
i see. but, shouldn't it be renamed `addElement`? (ie without the plural `s` at the end)

2021-12-02 15:14 UTC, merged