E2etest micronaut latest
EMResearch/EvoMaster pull request #464
Opened 2022-02-17 09:56 UTC by seran

Note: Latest version of Micronaut is 3.3.3 but when running tests it's very slow. Need more time to debug. At the same time 3.2.7 work well without any problems.

2022-02-17 10:21 UTC, ZhangMan1126 requested changes

2022-02-17 10:21 UTC, ZhangMan1126 commented on e2e-tests/micronaut-latest/pom.xml
> +            <dependency>
this might move to `<dependencyManagement>` of root `pom.xml`

2022-02-17 10:21 UTC, ZhangMan1126 commented on e2e-tests/micronaut-latest/pom.xml
> +        <dependency>
micronaut related dependencies might be configured in `dependencyManagement` of the root `pom.xml`.

2022-02-17 10:21 UTC, ZhangMan1126 commented on e2e-tests/micronaut-latest/pom.xml
> +                        </path>
this could be configured with the `pluginManagement` of the root `pom.xml`. then you do not need to refer to version info here.

2022-02-18 18:33 UTC, ZhangMan1126 commented
Hi @seran . thanks! I have no further comments. you could request Andrea's review

2022-02-21 08:38 UTC, arcuri82 requested changes

2022-02-21 08:38 UTC, arcuri82 commented on e2e-tests/micronaut-latest/pom.xml
> +        <version>1.3.1-SNAPSHOT</version>
update to current `1.4.1-SNAPSHOT`

2022-02-21 08:38 UTC, arcuri82 commented on e2e-tests/micronaut-latest/src/test/java/com/foo/micronaut/latest/MicronautTestController.java
> +    public Connection getConnection() {
this might now work... ie compilation error due to latest changes in `master` branch. pull from master, and update if needed

2022-02-21 08:38 UTC, arcuri82 commented on pom.xml
> +                <groupId>org.junit.jupiter</groupId>
i guess this should have `test` scope?
also, should be moved together close to the other JUnit dependencies

2022-02-23 20:55 UTC, merged

2022-02-23 21:05 UTC, seran commented
🥂