enable info collected during sut boot-time
EMResearch/EvoMaster pull request #504
Opened 2022-05-05 10:38 UTC by ZhangMan1126

manipluate executing action state
collect and restore objective info (such as targets and external service info) during the boot-time (only for JVM)
tests for checking whether the boot-time targets are covered with the exported targets file.

2022-05-06 07:07 UTC, arcuri82 requested changes

2022-05-06 07:07 UTC, arcuri82 commented on core/src/main/kotlin/org/evomaster/core/search/FitnessValue.kt
> +    fun unionWithBootTimeCoveredTargets(prefix: String?, idMapper: IdMapper, bootTimeInfoDto: BootTimeInfoDto?, unavailableBootTime: Int = -1): Triple<Int, Int, Int>{
the use of `Triple` is fine in a local scope, but not when returned by a public method, as it makes code harder to read. eg., how to understand what `first` and `third` are referring to semantically.
create a new class with meaningful names to replace this `Triple`

2022-05-06 07:07 UTC, arcuri82 commented on core/src/main/kotlin/org/evomaster/core/search/FitnessValue.kt
> +    fun unionWithBootTimeCoveredTargets(prefix: String?, idMapper: IdMapper, bootTimeInfoDto: BootTimeInfoDto?, unavailableBootTime: Int = -1): Triple<Int, Int, Int>{
the use of `Triple` is fine in a local scope, but not when returned by a public method, as it makes code harder to read. eg., how to understand what `first` and `third` are referring to semantically.
create a new class with meaningful names to replace this `Triple`

2022-05-06 07:07 UTC, arcuri82 commented on e2e-tests/spring-rest-openapi-v3/src/main/kotlin/com/foo/rest/examples/spring/openapi/v3/boottimetargets/BootTimeTargetsRest.kt
> +        // TODO might need a further check, targets for lines 24 and 25 seems to be skipped
yep, indeed, we do not instrument class initializers

2022-05-06 07:07 UTC, arcuri82 commented on e2e-tests/spring-rest-openapi-v3/src/main/kotlin/com/foo/rest/examples/spring/openapi/v3/boottimetargets/BootTimeTargetsRest.kt
> +        // TODO might need a further check, targets for lines 24 and 25 seems to be skipped
yep, indeed, we do not instrument class initializers

2022-05-06 08:43 UTC, seran reviewed
Thank you @ZhangMan1126. I have no comments.

2022-05-06 10:58 UTC, ZhangMan1126 commented on core/src/main/kotlin/org/evomaster/core/search/FitnessValue.kt
> +        return TargetStatisticTriple(bootTime.size, searchTime, bootTime.size + searchTime - duplicatedcounter)
maybe it only happens for class due to class load? 
to ensure that we avoid the repeated ones, we might still need to have a check on them

2022-05-06 11:19 UTC, arcuri82 commented on core/src/main/kotlin/org/evomaster/core/search/TargetStatisticTriple.kt
> +    val total: Int
@ZhangMan1126 hi. thx. wondering if this is related to handling of `firstTimeEncountered`, which might not have been reset, maybe?

2022-05-09 07:21 UTC, arcuri82 approved these changes

2022-05-09 07:21 UTC, merged