Client variable
EMResearch/EvoMaster pull request #515
Opened 2022-05-16 14:40 UTC by ZhangMan1126

use client variable for rpc function execution in the generated tests

2022-05-16 14:40 UTC, ZhangMan1126 commented
@arcuri82  please review this PR after the PR for `seedtest-deserialization` branch. thanks.

2022-05-18 08:34 UTC, arcuri82 requested changes

2022-05-18 08:34 UTC, arcuri82 commented on client-java/controller-api/src/main/java/org/evomaster/client/java/controller/api/dto/problem/rpc/RPCActionDto.java
> +    public String clientVariable;
bit confusing... add more info

2022-05-18 08:34 UTC, arcuri82 commented on client-java/controller/src/main/java/org/evomaster/client/java/controller/problem/rpc/schema/params/PrimitiveOrWrapperParam.java
> +    public Object convertValueTo(Object value){
haven't i seen this exact same function in the previous PR???

2022-05-18 10:55 UTC, merged