Dto reflection
EMResearch/EvoMaster pull request #790
Opened 2023-08-11 11:50 UTC by man-zhang

fix dto schema extraction for external services

2023-09-05 19:07 UTC, arcuri82 commented on client-java/controller-api/src/main/java/org/evomaster/client/java/controller/api/dto/SutInfoDto.java
>      }
wasn't this code done in another branch? am i looking at a branch that pull in from another branch that has not been merged yet? in that case, i should wait until the other branch is merged before looking into this one

2023-09-06 13:01 UTC, arcuri82 requested changes

2023-09-06 15:08 UTC, man-zhang commented on client-java/controller/src/test/java/com/thrift/example/artificial/PrivateFieldInRequestDto.java
>      private short priShort;
this is the case that exists in the industrial case study. the setter of the attribute might employ a bit different type. 
In order to support such a case, now we analyze the type of attribute and setter/getter (see `AccessibleSchema`).
If we do not support this, there will be problems in generated tests (eg, compile failed due to mismatched type).

2023-09-07 10:21 UTC, arcuri82 commented on client-java/controller/src/test/java/com/thrift/example/artificial/PrivateFieldInRequestDto.java
>      private short priShort;
@man-zhang ah, sorry, didn't realize it was just an example in a test... yes, we need to support all different types. but i guess most important is what defined in the getters, unless the fields are public

2023-09-07 10:22 UTC, arcuri82 approved these changes

2023-09-07 10:22 UTC, merged