Issue #873: Provide a more detailed error if the introspection query's connection fails
EMResearch/EvoMaster pull request #894
Opened 2024-02-03 17:52 UTC by marcellomaugeri

2024-02-04 21:12 UTC, arcuri82 requested changes
@marcellomaugeri  thx for providing a PR! see my comments

2024-02-04 21:12 UTC, arcuri82 commented on core/src/main/kotlin/org/evomaster/core/problem/graphql/IntrospectiveQuery.kt
> +        val response: Response?
thx. in contrast to Java, in Kotlin most statements are expressions. so can write something directly like `val response = try {...`

2024-02-04 21:12 UTC, arcuri82 commented on core/src/main/kotlin/org/evomaster/core/problem/graphql/IntrospectiveQuery.kt
> +        val response: Response?
also why nullable with `?` ? 
if want to check case for null, could make it non-null, with explicit throw exception after `try` with the `?:` Elvis operator

2024-02-04 21:12 UTC, arcuri82 commented on core/src/main/kotlin/org/evomaster/core/problem/graphql/IntrospectiveQuery.kt
> +                    throw e
the `throw SutProblemException(` should rather be done here, with `e.message` added to the message of the error, something like:
```
throw SutProblemException("Failed introspection query to '$graphQlEndpoint', please check connection and URL format. Error: ${e.message}" )
```

2024-02-04 21:12 UTC, arcuri82 commented on core/src/main/kotlin/org/evomaster/core/problem/graphql/IntrospectiveQuery.kt
> +        }
not needed here of this outer try/catch. see previous comment

2024-02-04 21:12 UTC, arcuri82 commented on core/src/main/kotlin/org/evomaster/core/problem/graphql/IntrospectiveQuery.kt
> +        val body = response?.readEntity(String::class.java)
not needed `?` if variable is made non-nullable, with explicit `?:` check on nullability (if needed)

2024-02-04 21:12 UTC, arcuri82 commented on core/src/main/kotlin/org/evomaster/core/search/service/SearchTimeController.kt
> +            }
what is the reason of this? why catching an exception and throwing it again without doing anything with it?

2024-03-04 00:48 UTC, marcellomaugeri commented
@arcuri82 Sorry for the delay in troubleshooting. I think it's all sorted now, I was a bit confused as I'm fairly new to Kotlin, thanks for the explanations. However I'm still not sure about the double try-catch to get the answer, could you please check again? Thank you.

2024-03-05 11:08 UTC, arcuri82 commented
hi @marcellomaugeri 
 sorry, but I don't understand why you are having a double-catch.
Can you please check the branch `related-to-pr-894`, to see if that solves the issue you have? 
thx

2024-03-10 19:02 UTC, marcellomaugeri commented
@arcuri82 yes, your branch solves the issue, thank you for your time and patience. I was overcomplicating things! Thank you for your suggestions, I am quite new to Kotlin and I got confused because the code was not compiling and then I added the double-catch, the rest you know

2024-03-10 20:30 UTC, closed without merging